language: java
sudo: false

jdk:
- openjdk8
- oraclejdk8

install: true
script: ./travis.sh
env:
- TEST=ci
- TEST=plugin SQ_VERSION=LATEST_RELEASE[6.7]
- TEST=plugin SQ_VERSION=LATEST_RELEASE[7.2]

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar'
  - '$HOME/jvm'
  - '$HOME/maven'

notifications:
  email:
  - jens@gerdes.digital
